# Generated by Django 3.2.17 on 2023-04-14 22:35

from django.db import migrations
from django.db import models

import teams.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'pending',
                'verbose_name_plural': 'pending list',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Choose role name that you need in your project',
                        max_length=128,
                        verbose_name='name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RoleTeam',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'role in team',
                'verbose_name_plural': 'roles in team',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Write title of your project',
                        max_length=64,
                        verbose_name='title',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Write description of your project',
                        verbose_name='description',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        help_text='Load image of your project',
                        null=True,
                        upload_to=teams.models.Team.get_upload_image,
                        verbose_name='image',
                    ),
                ),
                (
                    'presentation',
                    models.FileField(
                        blank=True,
                        help_text='Load presentation of your project',
                        null=True,
                        upload_to=teams.models.Team.get_upload_presentation,
                        verbose_name='presentation',
                    ),
                ),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
    ]
