# Generated by Django 3.2.17 on 2023-04-04 21:38

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion

import teams.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=64, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=teams.models.Team.get_upload_image,
                        verbose_name='',
                    ),
                ),
                (
                    'presentation',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=teams.models.Team.get_upload_presentation,
                        verbose_name='',
                    ),
                ),
                ('is_published', models.BooleanField(default=True)),
                (
                    'creator',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'languages',
                    models.ManyToManyField(
                        help_text='Specify team languages',
                        to='users.Language',
                        verbose_name='Languages',
                    ),
                ),
                (
                    'technologies',
                    models.ManyToManyField(
                        help_text='Specify technologies your team use',
                        to='users.Technology',
                        verbose_name='Technologies your team use',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RoleTeam',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role_default',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='teams.role',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='teams.team',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='teams.roleteam',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role_team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='teams.roleteam',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]