# Generated by Django 3.2.17 on 2023-04-12 18:34

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion

import teams.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20230412_2234'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.AlterModelOptions(
            name='pending',
            options={
                'verbose_name': 'pending',
                'verbose_name_plural': 'pending list',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='roleteam',
            options={
                'verbose_name': 'role in team',
                'verbose_name_plural': 'roles in team',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterField(
            model_name='member',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose roles in your project',
                on_delete=django.db.models.deletion.CASCADE,
                to='teams.roleteam',
            ),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(
                help_text='User for this role',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='pending',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose role that you want to be',
                on_delete=django.db.models.deletion.CASCADE,
                to='teams.roleteam',
            ),
        ),
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.OneToOneField(
                help_text='User for this pending',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(
                help_text='Choose role name that you need in your project',
                max_length=128,
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='roleteam',
            name='role_default',
            field=models.ForeignKey(
                help_text='Role from standard list',
                on_delete=django.db.models.deletion.CASCADE,
                to='teams.role',
            ),
        ),
        migrations.AlterField(
            model_name='roleteam',
            name='team',
            field=models.ForeignKey(
                help_text='Choose your teammate',
                on_delete=django.db.models.deletion.CASCADE,
                to='teams.team',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(
                help_text='Person who came up with this idea of project',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(
                help_text='Write description of your project',
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Load image of your project',
                null=True,
                upload_to=teams.models.Team.get_upload_image,
                verbose_name='image',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='languages',
            field=models.ManyToManyField(
                help_text='Specify team languages', to='users.Language'
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='presentation',
            field=models.FileField(
                blank=True,
                help_text='Load presentation of your project',
                null=True,
                upload_to=teams.models.Team.get_upload_presentation,
                verbose_name='presentation',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(
                help_text='Write title of your project',
                max_length=64,
                verbose_name='title',
            ),
        ),
    ]
