# Generated by Django 3.2.17 on 2023-04-14 22:35

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(
                help_text='Person who came up with this idea of project',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='team',
            name='language',
            field=models.ForeignKey(
                help_text='Specify team language',
                on_delete=django.db.models.deletion.CASCADE,
                to='users.language',
            ),
        ),
        migrations.AddField(
            model_name='team',
            name='technologies',
            field=models.ManyToManyField(
                help_text='Specify technologies your team use',
                to='users.Technology',
                verbose_name='Technologies your team use',
            ),
        ),
        migrations.AddField(
            model_name='roleteam',
            name='role_default',
            field=models.ForeignKey(
                help_text='Role from standard list',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roles',
                to='teams.role',
            ),
        ),
        migrations.AddField(
            model_name='roleteam',
            name='team',
            field=models.ForeignKey(
                help_text='Choose  your teammate',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roleteams',
                to='teams.team',
            ),
        ),
        migrations.AddField(
            model_name='pending',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose role that you want to be',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pendings',
                to='teams.roleteam',
            ),
        ),
        migrations.AddField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(
                help_text='User for this pending',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose roles in your project',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='teams.roleteam',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(
                help_text='User for this role',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
