# Generated by Django 3.2.17 on 2023-04-16 15:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230416_1953'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['-id'],
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='technologies',
            field=models.ManyToManyField(
                help_text='Specify technologies your team use',
                to='users.Technology',
                verbose_name='technologies your team use',
            ),
        ),
    ]
