# Generated by Django 3.2.17 on 2023-04-14 12:14

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20230412_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={
                'ordering': ['-id'],
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose roles in your project',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='teams.roleteam',
            ),
        ),
        migrations.AlterField(
            model_name='pending',
            name='role_team',
            field=models.ForeignKey(
                help_text='Choose role that you want to be',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pendings',
                to='teams.roleteam',
            ),
        ),
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(
                help_text='User for this pending',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='roleteam',
            name='role_default',
            field=models.ForeignKey(
                help_text='Role from standard list',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roles',
                to='teams.role',
            ),
        ),
        migrations.AlterField(
            model_name='roleteam',
            name='team',
            field=models.ForeignKey(
                help_text='Choose  your teammate',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='roleteams',
                to='teams.team',
            ),
        ),
    ]
