# Generated by Django 3.2.17 on 2023-04-02 16:47

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations
from django.db import models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'language',
                    models.CharField(
                        help_text='Specify the title of this language',
                        max_length=255,
                        verbose_name='Title of language',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'technology',
                    models.CharField(
                        help_text='Specify the title of this technology',
                        max_length=255,
                        verbose_name='Title of technology',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={
                            'unique': 'A user with that username already exists.'
                        },
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                (
                    'nickname',
                    models.CharField(
                        help_text='Name that other users will see',
                        max_length=255,
                        verbose_name='Your nickname',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        help_text="This email will be used by this website's owners and moderators to contact you",
                        max_length=254,
                        verbose_name='Your email',
                    ),
                ),
                (
                    'about_me',
                    models.TextField(
                        blank=True,
                        help_text='Mention everything you consider to be important',
                        max_length=10000,
                        null=True,
                        verbose_name='Tell more about yourself',
                    ),
                ),
                (
                    'github',
                    models.CharField(
                        help_text='Specify website to allow others check your projects',
                        max_length=255,
                        verbose_name='GitHub, Bitbucket or something similar',
                    ),
                ),
                (
                    'contact_data',
                    models.CharField(
                        help_text='Let other users contact you',
                        max_length=255,
                        verbose_name='Contact information',
                    ),
                ),
                (
                    'address',
                    models.CharField(
                        blank=True,
                        help_text='Specify your country and, if you want, city to help people living nearby find you',
                        max_length=255,
                        null=True,
                        verbose_name='Place where you live',
                    ),
                ),
                (
                    'resume',
                    models.FileField(
                        blank=True,
                        help_text='Show others your resume',
                        null=True,
                        upload_to='resumes/',
                        verbose_name='Resume',
                    ),
                ),
                (
                    'study_place_choose',
                    models.CharField(
                        choices=[
                            ('School', 'School'),
                            ('University', 'University'),
                        ],
                        help_text='Select place where you have studied',
                        max_length=255,
                        verbose_name='Place of studies',
                    ),
                ),
                (
                    'study_place',
                    models.CharField(
                        blank=True,
                        help_text='University or courses you have completed',
                        max_length=255,
                        null=True,
                        verbose_name='Where have you learned?',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'languages',
                    models.ManyToManyField(
                        help_text='Specify languages you know',
                        to='users.Language',
                        verbose_name='Languages you speak',
                    ),
                ),
                (
                    'technologies',
                    models.ManyToManyField(
                        help_text='Specify technologies you know or those, which you are still learning',
                        to='users.Technology',
                        verbose_name='Technologies you use',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
