# Generated by Django 3.2.17 on 2023-04-06 12:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='study_place',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='study_place_choose',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(
                blank=True,
                help_text='Specify your country and city to help people living nearby find you',
                max_length=255,
                null=True,
                verbose_name='Place where you live (country and city)',
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(
                blank=True,
                help_text='University you attend or completed',
                max_length=255,
                null=True,
                verbose_name='Where have you learned?',
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_choose',
            field=models.CharField(
                choices=[('School', 'School'), ('University', 'University')],
                default='School',
                help_text='Select place where you have studied',
                max_length=255,
                verbose_name='Education',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(
                blank=True,
                help_text='Mention everything you consider to be important',
                max_length=2000,
                null=True,
                verbose_name='Tell more about yourself',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254, verbose_name='email address'
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='technologies',
            field=models.ManyToManyField(
                help_text='Specify your stack of technologies',
                to='users.Technology',
                verbose_name='Technologies you use',
            ),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(
                help_text='Specify communication language',
                max_length=255,
                verbose_name='Language',
            ),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology',
            field=models.CharField(
                help_text='Specify technology',
                max_length=255,
                verbose_name='Technology',
            ),
        ),
    ]
