# Generated by Django 3.2.17 on 2023-04-12 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_squashed_0003_alter_customuser_education_choose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
    ]
