# Generated by Django 3.2.17 on 2023-04-16 15:53

import ckeditor.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text='Mention everything you consider to be important',
                max_length=2000,
                null=True,
                verbose_name='tell more about yourself',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(
                blank=True,
                help_text='Specify your country and city to help people living nearby find you',
                max_length=255,
                null=True,
                verbose_name='place where you live (country and city)',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_data',
            field=models.CharField(
                help_text='Let other users contact you',
                max_length=255,
                verbose_name='contact information',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(
                blank=True,
                help_text='University you attend or completed',
                max_length=255,
                null=True,
                verbose_name='where have you learned?',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_choose',
            field=models.CharField(
                choices=[('school', 'School'), ('university', 'University')],
                help_text='Select place where you have studied',
                max_length=255,
                verbose_name='education',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github',
            field=models.CharField(
                help_text='Specify website to allow others check your projects',
                max_length=255,
                verbose_name='gitHub, Bitbucket or something similar',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Your avatar',
                null=True,
                upload_to='user_avatars/',
                verbose_name='avatar',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=models.ManyToManyField(
                help_text='Specify languages you know',
                to='users.Language',
                verbose_name='languages you speak',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(
                help_text='Name that other users will see',
                max_length=255,
                verbose_name='your nickname',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(
                blank=True,
                help_text='Show others your resume',
                null=True,
                upload_to='resumes/',
                verbose_name='resume',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='technologies',
            field=models.ManyToManyField(
                help_text='Specify your stack of technologies',
                to='users.Technology',
                verbose_name='technologies you use',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(
                blank=True,
                help_text='Show others yourself',
                null=True,
                upload_to='user_pictures',
                verbose_name='user picture',
            ),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(
                help_text='Specify communication language',
                max_length=255,
                verbose_name='language',
            ),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology',
            field=models.CharField(
                help_text='Specify technology',
                max_length=255,
                verbose_name='technology',
            ),
        ),
    ]
