# Generated by Django 3.2.17 on 2023-04-13 18:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_squashed_0003_alter_customuser_education_choose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(
                blank=True,
                help_text='Show others yourself',
                null=True,
                upload_to='user_pictures',
                verbose_name='User picture',
            ),
        ),
    ]
