# Generated by Django 3.2.17 on 2023-04-06 12:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education_choose',
            field=models.CharField(
                choices=[('school', 'School'), ('university', 'University')],
                help_text='Select place where you have studied',
                max_length=255,
                verbose_name='Education',
            ),
        ),
    ]