# Generated by Django 3.2.17 on 2023-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230413_2227'),
        ('users', '0003_customuser_image'),
    ]

    operations = []
