version: '3.9'

services:
  flexwire:
    build:
      dockerfile: Dockerfile
      context: .
    image: flexwire:latest
    container_name: flexwire
    volumes:
      - static_volume:/yt/static
      - media_volume:/yt/media
    env_file:
      - ./.env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && ./manage.py runserver"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: flexwire-nginx
    image: flexwire-nginx
    volumes:
      - static_volume:/flexwire/static
      - media_volume:/flexwire/media
    depends_on:
      - flexwire
    ports:
      - "80:80"


volumes:
  static_volume:
  media_volume:
