[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "google"

[tool.djlint]
indent=2
ignore="H031"
exclude="activating_email.html"
